# Generated by Django 2.2.7 on 2019-11-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='me',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='friend',
            field=models.CharField(default='', max_length=100),
        ),
    ]
