# Generated by Django 2.2.7 on 2019-11-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191123_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='me',
            new_name='author',
        ),
    ]
