# Generated by Django 2.2.7 on 2019-11-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191123_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='details',
            field=models.PositiveSmallIntegerField(choices=[(1, 'food'), (2, 'clothing'), (3, 'groceries'), (4, 'hospital'), (5, 'trips'), (6, 'others')]),
        ),
    ]
