# Generated by Django 2.2.7 on 2019-11-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_friends'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
    ]
