# Generated by Django 2.2.7 on 2019-11-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191124_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='Friend',
        ),
    ]
