# Generated by Django 2.2.7 on 2019-11-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191124_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='Friend',
            new_name='friend',
        ),
    ]
