# Generated by Django 2.2.7 on 2019-11-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20191124_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='abs_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='friend',
            field=models.CharField(default='', max_length=100),
        ),
    ]
