# Generated by Django 2.2.7 on 2019-11-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20191125_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='author',
            new_name='author_name',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='friend_name',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.Friend'),
        ),
        migrations.AlterField(
            model_name='post',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='blog.Friend'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('friend_name', 'email')},
        ),
    ]
